import { and, count, desc, eq, isNull, sql } from 'drizzle-orm';

import type { Database } from '../../db/client.js';
import { sku } from '../../db/schema/catalogue.js';
import { stockItem, stockLedger } from '../../db/schema/inventory.js';
import { executor } from '../../db/transaction.js';

/**
 * Inventory data access.
 *
 * **Every query here is scoped by `storeId`, in the WHERE clause** — not by a check the caller
 * performs afterwards, and not by trusting that middleware got it right. A future caller
 * arriving from a CLI command or a background job inherits the same isolation.
 *
 * ## Why this file may name the `sku` table
 *
 * `dependency-cruiser`'s `no-cross-module-imports` forbids `modules/inventory` from importing
 * anything under `modules/catalogue` — including a type. But `schema-only-in-repositories`
 * explicitly permits any `*.repository.ts` to import any table, and `db/schema/` is not a
 * module. So the SKU liveness predicate lives here, in ONE statement, rather than being
 * fetched through a port and then re-checked.
 *
 * That is a deliberate, narrow use of that permission. It is confined to the join below and to
 * the same predicate in the two read methods; nothing here writes `sku`, and nothing here
 * decides anything about a SKU beyond whether it exists, belongs to this store, and is not
 * deleted.
 *
 * ## Why there is no `db.query.*` anywhere in this module
 *
 * `local/no-relational-api-in-inventory` forbids it, per docs/DECISIONS.md §6: `.for('update')`
 * exists on the query builder and not on the relational API, so the relational form compiles,
 * returns the right row, and takes no lock. Nothing here takes a lock — the atomic statement
 * below is why — but the rule guards the allocation increment that will.
 */

/**
 * Re-exported so the rest of the module can name a reason without importing a table.
 *
 * The list lives in the schema because the database CHECK constraint is its real enforcement
 * point, and `schema-only-in-repositories` means this file is the only one permitted to see
 * it. Re-exporting keeps one source of truth rather than a second copy in the DTO that could
 * silently drift from the constraint — the same discipline the catalogue applies to
 * `PRODUCT_STATUSES`.
 */
export { STOCK_REASONS, type StockReason } from '../../db/schema/inventory.js';

export type InventoryRepository = ReturnType<typeof createInventoryRepository>;

/**
 * A stock row as the rest of the system sees it.
 *
 * `storeId` is absent: tenancy is an invariant of the query rather than a field for a caller
 * to inspect. `skuId` and `skuCode` are both present — the id because a consumer needs the
 * relationship, the code because it is what a merchant reads and what the adjustment endpoint
 * accepts.
 */
export type StockRecord = {
  readonly skuId: string;
  readonly skuCode: string;
  readonly onHand: number;
  readonly reserved: number;
  /** Generated by PostgreSQL as `on_hand - reserved`. Never computed here. */
  readonly available: number;
  readonly createdAt: Date;
  readonly updatedAt: Date;
};

/**
 * One ledger entry as the rest of the system sees it.
 *
 * `storeId` is absent for the same reason. `actorUserId` IS present: an audit reader needs to
 * know who moved the stock, and the caller is authenticated staff of the owning store.
 */
export type StockLedgerRecord = {
  readonly id: string;
  readonly skuId: string;
  readonly delta: number;
  readonly onHandBefore: number;
  readonly onHandAfter: number;
  readonly reason: string;
  readonly note: string;
  readonly actorUserId: string;
  readonly requestId: string | null;
  readonly createdAt: Date;
};

/** The columns a stock read returns, joined to the SKU for its code. */
const STOCK_COLUMNS = {
  skuId: stockItem.skuId,
  skuCode: sku.code,
  onHand: stockItem.onHand,
  reserved: stockItem.reserved,
  available: stockItem.available,
  createdAt: stockItem.createdAt,
  updatedAt: stockItem.updatedAt,
} as const;

const LEDGER_COLUMNS = {
  id: stockLedger.id,
  skuId: stockLedger.skuId,
  delta: stockLedger.delta,
  onHandBefore: stockLedger.onHandBefore,
  onHandAfter: stockLedger.onHandAfter,
  reason: stockLedger.reason,
  note: stockLedger.note,
  actorUserId: stockLedger.actorUserId,
  requestId: stockLedger.requestId,
  createdAt: stockLedger.createdAt,
} as const;

export type InsertLedgerValues = {
  id: string;
  storeId: string;
  skuId: string;
  delta: number;
  onHandBefore: number;
  onHandAfter: number;
  reason: string;
  note: string;
  actorUserId: string;
  requestId: string | null;
};

/** What the atomic adjustment returns when it matched a row. */
export type AdjustmentOutcome = {
  readonly skuId: string;
  readonly onHandBefore: number;
  readonly onHandAfter: number;
  readonly reserved: number;
  readonly available: number;
};

export function createInventoryRepository(deps: { db: Database }) {
  const { db } = deps;

  /**
   * "This SKU is live and belongs to this store."
   *
   * One predicate, used identically by the reads and by the atomic adjustment, so a SKU can
   * never be readable but unadjustable (or the reverse) because two predicates drifted. Note
   * what is deliberately NOT here: `is_active`. Deactivation means "not sellable", not "not
   * stocked" — a merchant deactivates a SKU precisely in order to count or correct it, and
   * refusing adjustments would make the deactivated state a trap.
   */
  const liveSkuIn = (storeId: string) => and(eq(sku.storeId, storeId), isNull(sku.deletedAt));

  return {
    /**
     * One SKU's stock, by merchant code.
     *
     * A join to `sku`, which is correct here and cannot duplicate: `stock_item.sku_id` is the
     * primary key and `sku.id` is too, so the relationship is strictly one-to-one. That is the
     * opposite of the catalogue's product/SKU case, where a join multiplies rows and the
     * visibility predicate has to be an `EXISTS`.
     */
    async findStockByCode(params: {
      storeId: string;
      code: string;
    }): Promise<StockRecord | undefined> {
      const [row] = await executor(db)
        .select(STOCK_COLUMNS)
        .from(stockItem)
        .innerJoin(sku, eq(sku.id, stockItem.skuId))
        .where(
          and(
            eq(stockItem.storeId, params.storeId),
            eq(sku.code, params.code),
            liveSkuIn(params.storeId),
          ),
        )
        .limit(1);
      return row;
    },

    /**
     * A page of this store's stock, plus the total.
     *
     * The `total` uses the IDENTICAL predicate as the page — the rule §28 established for
     * product lists and the one a divergence mutation targets. Both count `stock_item` rows,
     * and the one-to-one join means a product with many SKUs cannot inflate either figure.
     *
     * Ordered by SKU code so a page is stable and a merchant can find a row; `sku_id` breaks
     * ties, though the unique index on `(store_id, code)` means there are none among live SKUs.
     */
    async listStockForStore(params: {
      storeId: string;
      limit: number;
      offset: number;
    }): Promise<{ items: StockRecord[]; total: number }> {
      const visible = and(
        eq(stockItem.storeId, params.storeId),
        eq(sku.id, stockItem.skuId),
        liveSkuIn(params.storeId),
      );

      const [items, [counted]] = await Promise.all([
        executor(db)
          .select(STOCK_COLUMNS)
          .from(stockItem)
          .innerJoin(sku, eq(sku.id, stockItem.skuId))
          .where(visible)
          .orderBy(sku.code, stockItem.skuId)
          .limit(params.limit)
          .offset(params.offset),
        executor(db)
          .select({ total: count() })
          .from(stockItem)
          .innerJoin(sku, eq(sku.id, stockItem.skuId))
          .where(visible),
      ]);

      return { items, total: Number(counted?.total ?? 0) };
    },

    /**
     * **The atomic adjustment. The most important statement in this module.**
     *
     * ONE `UPDATE`, which is the entire concurrency strategy. It enforces six things at once
     * and returns the resulting state, so nothing is ever read into JavaScript, adjusted there,
     * and written back:
     *
     *  1. store scope        — `stock_item.store_id = :storeId`
     *  2. the SKU exists     — the join to `sku`
     *  3. the SKU is not deleted — `sku.deleted_at IS NULL`
     *  4. the right SKU      — `sku.code = :code`
     *  5. the result is legal — `on_hand + :delta >= reserved`, which is simultaneously the
     *     non-negative rule and the reserved floor, since `reserved >= 0` is a CHECK
     *  6. the arithmetic     — `on_hand = on_hand + :delta`, evaluated by PostgreSQL
     *
     * ## Why not read-modify-write, and why not `SELECT ... FOR UPDATE`
     *
     * Measured against this PostgreSQL during the design review, two concurrent `+5` from 10:
     * read-modify-write produced **15**, losing an update. The atomic form produced **20**.
     * Twenty concurrent mixed adjustments converged on the exact arithmetic total.
     *
     * Worse, on two concurrent `-4` from 5, read-modify-write left **1 and reported BOTH as
     * successful** — four units vanished and no CHECK constraint fired, because every value
     * written was individually legal. **A CHECK constraint prevents negative numbers; it does
     * not prevent lost updates.** That is why the predicate is load-bearing and the CHECKs are
     * only a backstop.
     *
     * `SELECT ... FOR UPDATE` is also correct but was measured at roughly double the wall
     * clock, because the lock is held across application think-time rather than for one
     * statement — and it puts the arithmetic back in JavaScript, which is the shape that fails
     * above. It becomes genuinely necessary when a decision spans several rows (allocating a
     * multi-line order), which is a later increment.
     *
     * ## Reading the result
     *
     * Zero rows means "no such live SKU in this store" OR "insufficient stock" — the caller
     * disambiguates with a second store-scoped read, exactly as `transitionStatus` does in the
     * catalogue. `on_hand_before` is derived from the returned `on_hand` rather than read
     * separately, so the before/after pair is guaranteed to come from the same statement.
     */
    async adjustStock(params: {
      storeId: string;
      code: string;
      delta: number;
      at: Date;
    }): Promise<AdjustmentOutcome | undefined> {
      const [row] = await executor(db)
        .update(stockItem)
        .set({
          // PostgreSQL does the arithmetic. Never `onHand + delta` in JavaScript.
          onHand: sql`${stockItem.onHand} + ${params.delta}`,
          updatedAt: params.at,
        })
        .where(
          and(
            eq(stockItem.storeId, params.storeId),
            sql`${stockItem.skuId} = (
              select ${sku.id} from ${sku}
               where ${sku.id} = ${stockItem.skuId}
                 and ${sku.code} = ${params.code}
                 and ${sku.storeId} = ${params.storeId}
                 and ${sku.deletedAt} is null
            )`,
            sql`${stockItem.onHand} + ${params.delta} >= ${stockItem.reserved}`,
          ),
        )
        .returning({
          skuId: stockItem.skuId,
          onHandAfter: stockItem.onHand,
          reserved: stockItem.reserved,
          available: stockItem.available,
        });

      if (!row) return undefined;

      return {
        skuId: row.skuId,
        // Derived from the SAME statement's result, so the pair cannot come from two reads.
        onHandBefore: row.onHandAfter - params.delta,
        onHandAfter: row.onHandAfter,
        reserved: row.reserved,
        available: row.available,
      };
    },

    /** Append one ledger entry. There is no update and no delete — the table is append-only. */
    async insertLedgerEntry(values: InsertLedgerValues): Promise<StockLedgerRecord> {
      const [row] = await executor(db).insert(stockLedger).values(values).returning(LEDGER_COLUMNS);
      // Drizzle returns exactly one row for a single-row insert; a failure throws.
      return row!;
    },

    /**
     * Resolve a live SKU by code, for the two places that need its identity.
     *
     * Returns the id so the ledger entry and the event can name it, and so the adjustment can
     * tell "no such SKU" (404) from "insufficient stock" (409) after the atomic update matched
     * nothing. Store-scoped in the query, so another store's code is simply absent.
     */
    async findLiveSkuRefByCode(params: {
      storeId: string;
      code: string;
    }): Promise<{ id: string; isActive: boolean } | undefined> {
      const [row] = await executor(db)
        .select({ id: sku.id, isActive: sku.isActive })
        .from(sku)
        .where(and(eq(sku.code, params.code), liveSkuIn(params.storeId)))
        .limit(1);
      return row;
    },

    /**
     * One SKU's movement history, newest first, with the total.
     *
     * Scoped by `store_id` AND `sku_id`, matching `ix_stock_ledger_sku_time` exactly, so the
     * page needs no sort node. `created_at DESC, id DESC` is a total order even for two entries
     * written in the same millisecond, because `id` is UUIDv7 and therefore time-ordered.
     *
     * No join to `sku`: the ledger is history and must stay readable regardless of the SKU's
     * current state. The caller has already resolved the SKU, which is what enforces liveness
     * at the boundary rather than inside the history query.
     */
    async listLedgerForSku(params: {
      storeId: string;
      skuId: string;
      limit: number;
      offset: number;
    }): Promise<{ items: StockLedgerRecord[]; total: number }> {
      const scope = and(
        eq(stockLedger.storeId, params.storeId),
        eq(stockLedger.skuId, params.skuId),
      );

      const [items, [counted]] = await Promise.all([
        executor(db)
          .select(LEDGER_COLUMNS)
          .from(stockLedger)
          .where(scope)
          .orderBy(desc(stockLedger.createdAt), desc(stockLedger.id))
          .limit(params.limit)
          .offset(params.offset),
        executor(db).select({ total: count() }).from(stockLedger).where(scope),
      ]);

      return { items, total: Number(counted?.total ?? 0) };
    },

    /**
     * Create the projection row for a newly created SKU.
     *
     * Called by nothing in this increment's HTTP surface: the migration initialised every
     * existing SKU, and a SKU created afterwards needs a row too. Exposed so the composition
     * root can wire it to SKU creation without the catalogue module importing inventory —
     * see `container.ts`.
     *
     * `ON CONFLICT DO NOTHING` makes it idempotent, so a retry cannot fail on a row that is
     * already correct.
     */
    async initialiseStock(params: { skuId: string; storeId: string }): Promise<void> {
      await executor(db)
        .insert(stockItem)
        .values({ skuId: params.skuId, storeId: params.storeId, onHand: 0, reserved: 0 })
        .onConflictDoNothing({ target: stockItem.skuId });
    },
  };
}
