import type { JsonObject } from '../../shared/events.js';

/**
 * The inventory module's event and audit vocabulary.
 *
 * Constants rather than inline strings, for the reason the catalogue module states: an event
 * name is a published contract that consumers switch on, and a typo in a second literal is a
 * message nobody receives. Follows `catalogue.events.ts` exactly — no second event bus, no
 * second audit abstraction.
 */

/** `aggregate_type` for stock events. Answers "what happened to this SKU's stock?" as one query. */
export const STOCK_AGGREGATE = 'stock_item';

/**
 * One event type, deliberately.
 *
 * No `inventory.depleted` and no `inventory.low_stock`: a threshold is a merchandising
 * decision this increment has not been given, and an event with no consumer is a guess at one.
 * A consumer that cares about depletion can derive it from `onHandAfter === 0`, which is a fact
 * this payload already carries.
 */
export const STOCK_EVENTS = {
  adjusted: 'inventory.adjusted',
} as const;

/** The matching audit action. Same string, different vocabulary — one is read by code, one by people. */
export const STOCK_AUDIT = {
  adjusted: 'inventory.adjusted',
} as const;

/** The `resource_type` recorded on every inventory audit entry. */
export const STOCK_RESOURCE = 'stock_item';

/**
 * The payload for `inventory.adjusted`.
 *
 * Ids and immutable facts, per `shared/events.ts`. Every field is something a consumer cannot
 * cheaply re-derive:
 *
 *  - `skuId` identifies the aggregate; `skuCode` is carried because a code is freed for reuse
 *    when a SKU is deleted, so an old event's id alone stops identifying which SKU it meant.
 *  - `delta`, `onHandBefore` and `onHandAfter` are the arithmetic. A consumer given only the
 *    result cannot tell a restock from a correction; given only the delta it cannot tell
 *    whether stock ran out.
 *  - `available` is included because it is generated by the database, so a consumer computing
 *    `onHandAfter - reserved` itself would be duplicating the one authoritative definition.
 *  - `reason` is the technical vocabulary from the schema.
 *
 * Deliberately ABSENT: `note`, which is free operator text and may contain anything, and the
 * actor. An event is a fact about the domain; WHO performed it belongs in the audit trail,
 * which has access controls an event stream does not.
 */
export function stockEventPayload(record: {
  skuId: string;
  skuCode: string;
  delta: number;
  onHandBefore: number;
  onHandAfter: number;
  available: number;
  reason: string;
}): JsonObject {
  return {
    skuId: record.skuId,
    skuCode: record.skuCode,
    delta: record.delta,
    onHandBefore: record.onHandBefore,
    onHandAfter: record.onHandAfter,
    available: record.available,
    reason: record.reason,
  };
}
