import { and, count, desc, eq, isNull, sql } from 'drizzle-orm';

import type { Database } from '../../db/client.js';
import { sku } from '../../db/schema/catalogue.js';
import {
  RESERVATION_HELD,
  stockItem,
  stockLedger,
  stockReservation,
  type ReservationSettledReason,
  type ReservationStatus,
} from '../../db/schema/inventory.js';
import { executor } from '../../db/transaction.js';

/**
 * Inventory data access.
 *
 * **Every query here is scoped by `storeId`, in the WHERE clause** — not by a check the caller
 * performs afterwards, and not by trusting that middleware got it right. A future caller
 * arriving from a CLI command or a background job inherits the same isolation.
 *
 * ## Why this file may name the `sku` table
 *
 * `dependency-cruiser`'s `no-cross-module-imports` forbids `modules/inventory` from importing
 * anything under `modules/catalogue` — including a type. But `schema-only-in-repositories`
 * explicitly permits any `*.repository.ts` to import any table, and `db/schema/` is not a
 * module. So the SKU liveness predicate lives here, in ONE statement, rather than being
 * fetched through a port and then re-checked.
 *
 * That is a deliberate, narrow use of that permission. It is confined to the join below and to
 * the same predicate in the two read methods; nothing here writes `sku`, and nothing here
 * decides anything about a SKU beyond whether it exists, belongs to this store, and is not
 * deleted.
 *
 * ## Why there is no `db.query.*` anywhere in this module
 *
 * `local/no-relational-api-in-inventory` forbids it, per docs/DECISIONS.md §6: `.for('update')`
 * exists on the query builder and not on the relational API, so the relational form compiles,
 * returns the right row, and takes no lock. Nothing here takes a lock — the atomic statement
 * below is why — but the rule guards the allocation increment that will.
 */

/**
 * Re-exported so the rest of the module can name a reason without importing a table.
 *
 * The list lives in the schema because the database CHECK constraint is its real enforcement
 * point, and `schema-only-in-repositories` means this file is the only one permitted to see
 * it. Re-exporting keeps one source of truth rather than a second copy in the DTO that could
 * silently drift from the constraint — the same discipline the catalogue applies to
 * `PRODUCT_STATUSES`.
 */
export {
  RESERVATION_HELD,
  RESERVATION_SETTLED_REASONS,
  RESERVATION_STATUSES,
  STOCK_REASONS,
  type ReservationSettledReason,
  type ReservationStatus,
  type StockReason,
} from '../../db/schema/inventory.js';

export type InventoryRepository = ReturnType<typeof createInventoryRepository>;

/**
 * A stock row as the rest of the system sees it.
 *
 * `storeId` is absent: tenancy is an invariant of the query rather than a field for a caller
 * to inspect. `skuId` and `skuCode` are both present — the id because a consumer needs the
 * relationship, the code because it is what a merchant reads and what the adjustment endpoint
 * accepts.
 */
export type StockRecord = {
  readonly skuId: string;
  readonly skuCode: string;
  readonly onHand: number;
  readonly reserved: number;
  /** Generated by PostgreSQL as `on_hand - reserved`. Never computed here. */
  readonly available: number;
  readonly createdAt: Date;
  readonly updatedAt: Date;
};

/**
 * One ledger entry as the rest of the system sees it.
 *
 * `storeId` is absent for the same reason. `actorUserId` IS present: an audit reader needs to
 * know who moved the stock, and the caller is authenticated staff of the owning store.
 */
export type StockLedgerRecord = {
  readonly id: string;
  readonly skuId: string;
  readonly delta: number;
  readonly onHandBefore: number;
  readonly onHandAfter: number;
  readonly reason: string;
  readonly note: string;
  readonly actorUserId: string;
  readonly requestId: string | null;
  readonly createdAt: Date;
};

/** The columns a stock read returns, joined to the SKU for its code. */
const STOCK_COLUMNS = {
  skuId: stockItem.skuId,
  skuCode: sku.code,
  onHand: stockItem.onHand,
  reserved: stockItem.reserved,
  available: stockItem.available,
  createdAt: stockItem.createdAt,
  updatedAt: stockItem.updatedAt,
} as const;

const LEDGER_COLUMNS = {
  id: stockLedger.id,
  skuId: stockLedger.skuId,
  delta: stockLedger.delta,
  onHandBefore: stockLedger.onHandBefore,
  onHandAfter: stockLedger.onHandAfter,
  reason: stockLedger.reason,
  note: stockLedger.note,
  actorUserId: stockLedger.actorUserId,
  requestId: stockLedger.requestId,
  createdAt: stockLedger.createdAt,
} as const;

export type InsertLedgerValues = {
  id: string;
  storeId: string;
  skuId: string;
  delta: number;
  onHandBefore: number;
  onHandAfter: number;
  reason: string;
  note: string;
  actorUserId: string;
  requestId: string | null;
};

/** What the atomic adjustment returns when it matched a row. */
export type AdjustmentOutcome = {
  readonly skuId: string;
  readonly onHandBefore: number;
  readonly onHandAfter: number;
  readonly reserved: number;
  readonly available: number;
};

export function createInventoryRepository(deps: { db: Database }) {
  const { db } = deps;

  /**
   * "This SKU is live and belongs to this store."
   *
   * One predicate, used identically by the reads and by the atomic adjustment, so a SKU can
   * never be readable but unadjustable (or the reverse) because two predicates drifted. Note
   * what is deliberately NOT here: `is_active`. Deactivation means "not sellable", not "not
   * stocked" — a merchant deactivates a SKU precisely in order to count or correct it, and
   * refusing adjustments would make the deactivated state a trap.
   */
  const liveSkuIn = (storeId: string) => and(eq(sku.storeId, storeId), isNull(sku.deletedAt));

  return {
    /**
     * One SKU's stock, by merchant code.
     *
     * A join to `sku`, which is correct here and cannot duplicate: `stock_item.sku_id` is the
     * primary key and `sku.id` is too, so the relationship is strictly one-to-one. That is the
     * opposite of the catalogue's product/SKU case, where a join multiplies rows and the
     * visibility predicate has to be an `EXISTS`.
     */
    async findStockByCode(params: {
      storeId: string;
      code: string;
    }): Promise<StockRecord | undefined> {
      const [row] = await executor(db)
        .select(STOCK_COLUMNS)
        .from(stockItem)
        .innerJoin(sku, eq(sku.id, stockItem.skuId))
        .where(
          and(
            eq(stockItem.storeId, params.storeId),
            eq(sku.code, params.code),
            liveSkuIn(params.storeId),
          ),
        )
        .limit(1);
      return row;
    },

    /**
     * A page of this store's stock, plus the total.
     *
     * The `total` uses the IDENTICAL predicate as the page — the rule §28 established for
     * product lists and the one a divergence mutation targets. Both count `stock_item` rows,
     * and the one-to-one join means a product with many SKUs cannot inflate either figure.
     *
     * Ordered by SKU code so a page is stable and a merchant can find a row; `sku_id` breaks
     * ties, though the unique index on `(store_id, code)` means there are none among live SKUs.
     */
    async listStockForStore(params: {
      storeId: string;
      limit: number;
      offset: number;
    }): Promise<{ items: StockRecord[]; total: number }> {
      const visible = and(
        eq(stockItem.storeId, params.storeId),
        eq(sku.id, stockItem.skuId),
        liveSkuIn(params.storeId),
      );

      const [items, [counted]] = await Promise.all([
        executor(db)
          .select(STOCK_COLUMNS)
          .from(stockItem)
          .innerJoin(sku, eq(sku.id, stockItem.skuId))
          .where(visible)
          .orderBy(sku.code, stockItem.skuId)
          .limit(params.limit)
          .offset(params.offset),
        executor(db)
          .select({ total: count() })
          .from(stockItem)
          .innerJoin(sku, eq(sku.id, stockItem.skuId))
          .where(visible),
      ]);

      return { items, total: Number(counted?.total ?? 0) };
    },

    /**
     * **The atomic adjustment. The most important statement in this module.**
     *
     * ONE `UPDATE`, which is the entire concurrency strategy. It enforces six things at once
     * and returns the resulting state, so nothing is ever read into JavaScript, adjusted there,
     * and written back:
     *
     *  1. store scope        — `stock_item.store_id = :storeId`
     *  2. the SKU exists     — the join to `sku`
     *  3. the SKU is not deleted — `sku.deleted_at IS NULL`
     *  4. the right SKU      — `sku.code = :code`
     *  5. the result is legal — `on_hand + :delta >= reserved`, which is simultaneously the
     *     non-negative rule and the reserved floor, since `reserved >= 0` is a CHECK
     *  6. the arithmetic     — `on_hand = on_hand + :delta`, evaluated by PostgreSQL
     *
     * ## Why not read-modify-write, and why not `SELECT ... FOR UPDATE`
     *
     * Measured against this PostgreSQL during the design review, two concurrent `+5` from 10:
     * read-modify-write produced **15**, losing an update. The atomic form produced **20**.
     * Twenty concurrent mixed adjustments converged on the exact arithmetic total.
     *
     * Worse, on two concurrent `-4` from 5, read-modify-write left **1 and reported BOTH as
     * successful** — four units vanished and no CHECK constraint fired, because every value
     * written was individually legal. **A CHECK constraint prevents negative numbers; it does
     * not prevent lost updates.** That is why the predicate is load-bearing and the CHECKs are
     * only a backstop.
     *
     * `SELECT ... FOR UPDATE` is also correct but was measured at roughly double the wall
     * clock, because the lock is held across application think-time rather than for one
     * statement — and it puts the arithmetic back in JavaScript, which is the shape that fails
     * above. It becomes genuinely necessary when a decision spans several rows (allocating a
     * multi-line order), which is a later increment.
     *
     * ## Reading the result
     *
     * Zero rows means "no such live SKU in this store" OR "insufficient stock" — the caller
     * disambiguates with a second store-scoped read, exactly as `transitionStatus` does in the
     * catalogue. `on_hand_before` is derived from the returned `on_hand` rather than read
     * separately, so the before/after pair is guaranteed to come from the same statement.
     */
    async adjustStock(params: {
      storeId: string;
      code: string;
      delta: number;
      at: Date;
    }): Promise<AdjustmentOutcome | undefined> {
      const [row] = await executor(db)
        .update(stockItem)
        .set({
          // PostgreSQL does the arithmetic. Never `onHand + delta` in JavaScript.
          onHand: sql`${stockItem.onHand} + ${params.delta}`,
          updatedAt: params.at,
        })
        .where(
          and(
            eq(stockItem.storeId, params.storeId),
            sql`${stockItem.skuId} = (
              select ${sku.id} from ${sku}
               where ${sku.id} = ${stockItem.skuId}
                 and ${sku.code} = ${params.code}
                 and ${sku.storeId} = ${params.storeId}
                 and ${sku.deletedAt} is null
            )`,
            sql`${stockItem.onHand} + ${params.delta} >= ${stockItem.reserved}`,
          ),
        )
        .returning({
          skuId: stockItem.skuId,
          onHandAfter: stockItem.onHand,
          reserved: stockItem.reserved,
          available: stockItem.available,
        });

      if (!row) return undefined;

      return {
        skuId: row.skuId,
        // Derived from the SAME statement's result, so the pair cannot come from two reads.
        onHandBefore: row.onHandAfter - params.delta,
        onHandAfter: row.onHandAfter,
        reserved: row.reserved,
        available: row.available,
      };
    },

    /* ── Fulfilment (Increment 37) ────────────────────────────────────────── */

    /**
     * One order's reservations that fulfilment must act on, with their current state.
     *
     * Read INSIDE the fulfilment transaction, after the order lock, so the set cannot change
     * underneath the decision. Ordered by `sku_id` ascending — the deterministic lock order
     * Increment 35 established, applied here because the caller will take a `stock_item` row
     * lock per SKU and two concurrent fulfilments of different orders sharing SKUs would
     * otherwise be able to form a wait cycle.
     *
     * Returns every non-released reservation, not only the committed ones, because the caller
     * has to distinguish three different answers: nothing to fulfil, a COD order still `held`,
     * and an order already `fulfilled`. Filtering here would collapse them into one.
     */
    async listFulfillableReservations(params: {
      orderId: string;
      storeId: string;
    }): Promise<{ skuId: string; quantity: number; status: string }[]> {
      return executor(db)
        .select({
          skuId: stockReservation.skuId,
          quantity: stockReservation.quantity,
          status: stockReservation.status,
        })
        .from(stockReservation)
        .where(
          and(
            eq(stockReservation.orderId, params.orderId),
            eq(stockReservation.storeId, params.storeId),
          ),
        )
        .orderBy(stockReservation.skuId);
    },

    /**
     * **The physical movement. The only statement in this codebase that decreases `on_hand`.**
     *
     * One conditional `UPDATE`, the same shape as `reserveForSku` and for the same reasons.
     * Both counters fall by the same amount, so `available = on_hand - reserved` is UNCHANGED —
     * correct, because the units stopped being sellable when they were reserved, not now.
     *
     * Three predicates, each load-bearing:
     *
     *  - `store_id` — tenancy, from the locked reservation row, never from caller input.
     *  - `on_hand >= :quantity` — **negative physical stock is impossible.** Also the reason
     *    this is not a bare decrement: a divergence must fail rather than write a nonsense row.
     *  - `reserved >= :quantity` — the units being shipped must be the ones that were held.
     *
     * `ck_stock_on_hand_non_negative` and `ck_stock_reserved_within_on_hand` are backstops
     * behind those predicates. Note the second holds automatically: if `reserved <= on_hand`
     * before, then `reserved - q <= on_hand - q` after.
     *
     * `RETURNING` gives both sides of the arithmetic from the SAME statement, so the ledger's
     * `on_hand_before`/`on_hand_after` pair cannot come from two different reads — the property
     * §39 built `adjustStock` around.
     *
     * `undefined` means the predicates did not hold, which for a caller that has already locked
     * the order and read a `committed` reservation means the projection has DIVERGED. The
     * service raises `InvariantViolation` rather than shipping stock it cannot account for.
     */
    async fulfilStockForSku(params: {
      skuId: string;
      storeId: string;
      quantity: number;
      at: Date;
    }): Promise<{ onHandBefore: number; onHandAfter: number; available: number } | undefined> {
      const [row] = await executor(db)
        .update(stockItem)
        .set({
          // PostgreSQL does the arithmetic. Never in JavaScript.
          onHand: sql`${stockItem.onHand} - ${params.quantity}`,
          reserved: sql`${stockItem.reserved} - ${params.quantity}`,
          updatedAt: params.at,
        })
        .where(
          and(
            eq(stockItem.skuId, params.skuId),
            eq(stockItem.storeId, params.storeId),
            sql`${stockItem.onHand} >= ${params.quantity}`,
            sql`${stockItem.reserved} >= ${params.quantity}`,
          ),
        )
        .returning({
          onHandAfter: stockItem.onHand,
          available: stockItem.available,
        });

      if (!row) return undefined;

      return {
        /* Derived from the same statement's result, so the pair describes one moment. */
        onHandBefore: row.onHandAfter + params.quantity,
        onHandAfter: row.onHandAfter,
        available: row.available,
      };
    },

    /**
     * Move one order's reservations to a terminal fulfilment state. CAS-protected.
     *
     * `WHERE status = :fromStatus` is the compare-and-swap: a second fulfilment of the same
     * order matches nothing, returns no rows, and therefore performs no second stock movement
     * and writes no second ledger entry. That guarantee is independent of any lock the caller
     * holds, which is what makes a duplicate staff click safe.
     *
     * `fulfilled_at` is a NEW column rather than a re-stamp of `settled_at`, so the moment the
     * sale was committed survives the moment it shipped — see the schema comment.
     */
    async fulfilReservationsForOrder(params: {
      orderId: string;
      storeId: string;
      fromStatus: ReservationStatus;
      at: Date;
    }): Promise<{ skuId: string; quantity: number }[]> {
      return executor(db)
        .update(stockReservation)
        .set({
          status: 'fulfilled',
          settledReason: 'shipment_fulfilled',
          fulfilledAt: params.at,
        })
        .where(
          and(
            eq(stockReservation.orderId, params.orderId),
            eq(stockReservation.storeId, params.storeId),
            eq(stockReservation.status, params.fromStatus),
          ),
        )
        .returning({
          skuId: stockReservation.skuId,
          quantity: stockReservation.quantity,
        });
    },

    /**
     * Commit one order's HELD reservations without a payment success. **COD only.**
     *
     * The explicit mechanism the approved COD rule requires. A COD payment never terminalises,
     * so its reservation sits `held` forever, and `held -> fulfilled` is deliberately illegal.
     * Rather than inventing a payment transition — forbidden — fulfilment performs this
     * `held -> committed` first, in the same transaction, and then fulfils normally.
     *
     * The reason is `cod_fulfilment`, NOT `payment_succeeded`: the money has not been received,
     * and a reason claiming otherwise would misreport an unpaid sale. **Nothing about the
     * payment row changes.**
     *
     * `reserved` does not move — commit never moves it, exactly as payment-success commit does
     * not — so the reconciliation invariant holds throughout: the units are still counted in
     * `reserved` right up until `fulfilStockForSku` takes them out.
     */
    async commitReservationsForCodFulfilment(params: {
      orderId: string;
      storeId: string;
      at: Date;
    }): Promise<{ skuId: string; quantity: number }[]> {
      return executor(db)
        .update(stockReservation)
        .set({
          status: 'committed',
          settledReason: 'cod_fulfilment',
          settledAt: params.at,
        })
        .where(
          and(
            eq(stockReservation.orderId, params.orderId),
            eq(stockReservation.storeId, params.storeId),
            eq(stockReservation.status, RESERVATION_HELD),
          ),
        )
        .returning({
          skuId: stockReservation.skuId,
          quantity: stockReservation.quantity,
        });
    },

    /** Append one ledger entry. There is no update and no delete — the table is append-only. */
    async insertLedgerEntry(values: InsertLedgerValues): Promise<StockLedgerRecord> {
      const [row] = await executor(db).insert(stockLedger).values(values).returning(LEDGER_COLUMNS);
      // Drizzle returns exactly one row for a single-row insert; a failure throws.
      return row!;
    },

    /**
     * Resolve a live SKU by code, for the two places that need its identity.
     *
     * Returns the id so the ledger entry and the event can name it, and so the adjustment can
     * tell "no such SKU" (404) from "insufficient stock" (409) after the atomic update matched
     * nothing. Store-scoped in the query, so another store's code is simply absent.
     */
    async findLiveSkuRefByCode(params: {
      storeId: string;
      code: string;
    }): Promise<{ id: string; isActive: boolean } | undefined> {
      const [row] = await executor(db)
        .select({ id: sku.id, isActive: sku.isActive })
        .from(sku)
        .where(and(eq(sku.code, params.code), liveSkuIn(params.storeId)))
        .limit(1);
      return row;
    },

    /**
     * One SKU's movement history, newest first, with the total.
     *
     * Scoped by `store_id` AND `sku_id`, matching `ix_stock_ledger_sku_time` exactly, so the
     * page needs no sort node. `created_at DESC, id DESC` is a total order even for two entries
     * written in the same millisecond, because `id` is UUIDv7 and therefore time-ordered.
     *
     * No join to `sku`: the ledger is history and must stay readable regardless of the SKU's
     * current state. The caller has already resolved the SKU, which is what enforces liveness
     * at the boundary rather than inside the history query.
     */
    async listLedgerForSku(params: {
      storeId: string;
      skuId: string;
      limit: number;
      offset: number;
    }): Promise<{ items: StockLedgerRecord[]; total: number }> {
      const scope = and(
        eq(stockLedger.storeId, params.storeId),
        eq(stockLedger.skuId, params.skuId),
      );

      const [items, [counted]] = await Promise.all([
        executor(db)
          .select(LEDGER_COLUMNS)
          .from(stockLedger)
          .where(scope)
          .orderBy(desc(stockLedger.createdAt), desc(stockLedger.id))
          .limit(params.limit)
          .offset(params.offset),
        executor(db).select({ total: count() }).from(stockLedger).where(scope),
      ]);

      return { items, total: Number(counted?.total ?? 0) };
    },

    /**
     * Create the projection row for a newly created SKU.
     *
     * Called by nothing in this increment's HTTP surface: the migration initialised every
     * existing SKU, and a SKU created afterwards needs a row too. Exposed so the composition
     * root can wire it to SKU creation without the catalogue module importing inventory —
     * see `container.ts`.
     *
     * `ON CONFLICT DO NOTHING` makes it idempotent, so a retry cannot fail on a row that is
     * already correct.
     */
    /* ── Reservation ──────────────────────────────────────────────────────── */

    /**
     * **Take units for one SKU. The concurrency primitive of the reservation feature.**
     *
     * ONE conditional `UPDATE`, the same shape and for the same reasons as `adjustStock`
     * above. It enforces three things at once and returns the resulting state, so no stock
     * figure is ever read into JavaScript, decided upon, and written back:
     *
     *  1. store scope     — `store_id = :storeId`
     *  2. the arithmetic  — `reserved = reserved + :quantity`, evaluated by PostgreSQL
     *  3. legality        — `available >= :quantity`
     *
     * `available` rather than a restatement of `on_hand - reserved`, because `available` is the
     * schema's ONE authoritative definition of availability. It is a `STORED` generated column,
     * so every committed row version carries a materialised value that PostgreSQL itself kept
     * consistent — there is no second place the formula could be written differently.
     *
     * ## Why two customers cannot both take the last unit
     *
     * `on_hand = 1, reserved = 0, available = 1`. Both request 1.
     *
     * T1 issues the `UPDATE`, matches, takes a row lock, writes `reserved = 1`, holds the lock
     * to commit. T2 issues the same statement, reaches the same row, finds it locked, and
     * BLOCKS. T1 commits. T2 unblocks — and under READ COMMITTED it does not proceed with the
     * row version it first read: PostgreSQL re-fetches the newly committed version and
     * **re-evaluates this `WHERE` clause against it** (the EvalPlanQual mechanism). That
     * version has `available = 0`, `0 >= 1` is false, the row is skipped, and the statement
     * reports **zero rows**. Exactly one succeeds.
     *
     * That re-evaluation is the whole guarantee, and it is why read-then-write is not merely
     * slower but WRONG: two `SELECT`s would both see `available = 1`, both compute a legal
     * result, and both write it. `adjustStock`'s header records this measured on this
     * PostgreSQL — two concurrent `-4` from 5 left 1 and reported BOTH successful, with no
     * CHECK constraint violated, because every value written was individually legal.
     *
     * ## Why there is no `SELECT ... FOR UPDATE`
     *
     * `FOR UPDATE` is necessary when one row's decision depends on READING ANOTHER ROW — you
     * must pin several rows, then decide. That is not the case here: a cart line's availability
     * is a function of its own `stock_item` row and nothing else, so every decision is a
     * single-row decision and the conditional `UPDATE` covers it. Adding `FOR UPDATE` would put
     * the arithmetic back in JavaScript — the shape that loses updates — and hold locks across
     * application think-time, measured at roughly double the wall clock.
     *
     * `docs/DECISIONS.md` §39 anticipated that this increment would need it. Following the code
     * it does not, and the divergence is approved and recorded.
     *
     * **It becomes necessary the moment a rule spans rows**: a kit or bundle where reserving A
     * is only legal if B is also available, an all-or-nothing multi-location allocation, or any
     * decision that must read one SKU's stock to decide another's. At that point this method is
     * the wrong primitive and the increment introducing such a rule must revisit it.
     *
     * ## Reading the result
     *
     * `undefined` means the update matched nothing, which is *insufficient stock*, *no
     * `stock_item` row for this SKU*, or *the SKU is not in this store* — indistinguishable
     * here by design, exactly as in `adjustStock`. The caller has already proven the SKU is
     * live and in-store (checkout's purchasability gate), and a missing projection row means
     * zero available, so the service treats all three as insufficient.
     */
    async reserveForSku(params: {
      skuId: string;
      storeId: string;
      quantity: number;
      at: Date;
    }): Promise<{ reserved: number; available: number } | undefined> {
      const [row] = await executor(db)
        .update(stockItem)
        .set({
          // PostgreSQL does the arithmetic. Never `reserved + quantity` in JavaScript.
          reserved: sql`${stockItem.reserved} + ${params.quantity}`,
          updatedAt: params.at,
        })
        .where(
          and(
            eq(stockItem.skuId, params.skuId),
            eq(stockItem.storeId, params.storeId),
            sql`${stockItem.available} >= ${params.quantity}`,
          ),
        )
        .returning({ reserved: stockItem.reserved, available: stockItem.available });

      return row;
    },

    /**
     * Give units back for one SKU.
     *
     * The mirror of `reserveForSku`, and the ONLY statement that decreases `reserved`. Its
     * `reserved >= :quantity` predicate should never fail: the caller reaches it only with a
     * row it just moved out of `held`, and a held reservation is by construction included in
     * the counter. So `undefined` here does not mean "insufficient" — it means the projection
     * has DIVERGED from the reservation rows, and the service raises `InvariantViolation`
     * rather than silently under-releasing.
     *
     * Kept as a guarded conditional update rather than a bare decrement precisely so that
     * divergence surfaces as a loud failure instead of driving the counter negative and
     * tripping `ck_stock_reserved_non_negative` with a less informative error.
     */
    async releaseForSku(params: {
      skuId: string;
      storeId: string;
      quantity: number;
      at: Date;
    }): Promise<{ reserved: number; available: number } | undefined> {
      const [row] = await executor(db)
        .update(stockItem)
        .set({
          reserved: sql`${stockItem.reserved} - ${params.quantity}`,
          updatedAt: params.at,
        })
        .where(
          and(
            eq(stockItem.skuId, params.skuId),
            eq(stockItem.storeId, params.storeId),
            sql`${stockItem.reserved} >= ${params.quantity}`,
          ),
        )
        .returning({ reserved: stockItem.reserved, available: stockItem.available });

      return row;
    },

    /**
     * Record the reservations, one row per line, all `held`.
     *
     * One statement for N rows. Called only after every `reserveForSku` has succeeded, so a
     * partially-reserved order never leaves reservation rows behind — and because the whole
     * thing is one transaction, a later failure removes both the rows and the counter
     * increments together.
     *
     * No `onConflictDoNothing`: a conflict on `pk_stock_reservation` means this order already
     * has a reservation for that SKU, which is a bug worth failing on rather than swallowing.
     */
    async insertReservations(
      rows: readonly {
        orderId: string;
        skuId: string;
        storeId: string;
        quantity: number;
      }[],
    ): Promise<void> {
      if (rows.length === 0) return;
      await executor(db)
        .insert(stockReservation)
        .values(rows.map((row) => ({ ...row, status: RESERVATION_HELD })));
    },

    /**
     * **Settle every held reservation for one order. The exactly-once guarantee.**
     *
     * One conditional `UPDATE` whose `status = 'held'` predicate is the compare-and-swap: a
     * second settlement of the same order matches nothing, returns no rows, and therefore
     * drives no counter change. That property is independent of any lock the caller holds,
     * which is what makes repeated cancellation and duplicate webhooks safe even if a future
     * code path reaches them by another route.
     *
     * The same predicate is why a `committed` reservation can never be released: it is not
     * `held`, so no release statement can match it. Structural, not conditional.
     *
     * `RETURNING sku_id, quantity` is what the caller decrements by — the settled rows and the
     * counter movements come from the SAME statement, so they cannot disagree.
     *
     * Rows for different orders never contend, because the primary key leads on `order_id`.
     */
    async settleReservationsForOrder(params: {
      orderId: string;
      storeId: string;
      toStatus: 'released' | 'committed';
      reason: ReservationSettledReason;
      at: Date;
    }): Promise<{ skuId: string; quantity: number }[]> {
      return executor(db)
        .update(stockReservation)
        .set({
          status: params.toStatus,
          settledReason: params.reason,
          settledAt: params.at,
        })
        .where(
          and(
            eq(stockReservation.orderId, params.orderId),
            eq(stockReservation.storeId, params.storeId),
            eq(stockReservation.status, RESERVATION_HELD),
          ),
        )
        .returning({
          skuId: stockReservation.skuId,
          quantity: stockReservation.quantity,
        });
    },

    /** One order's reservations, for tests and for support answering "what did this hold?". */
    async listReservationsForOrder(params: { orderId: string; storeId: string }): Promise<
      {
        skuId: string;
        quantity: number;
        status: string;
        settledReason: string | null;
        heldAt: Date;
        settledAt: Date | null;
      }[]
    > {
      return executor(db)
        .select({
          skuId: stockReservation.skuId,
          quantity: stockReservation.quantity,
          status: stockReservation.status,
          settledReason: stockReservation.settledReason,
          heldAt: stockReservation.heldAt,
          settledAt: stockReservation.settledAt,
        })
        .from(stockReservation)
        .where(
          and(
            eq(stockReservation.orderId, params.orderId),
            eq(stockReservation.storeId, params.storeId),
          ),
        )
        .orderBy(stockReservation.skuId);
    },

    async initialiseStock(params: { skuId: string; storeId: string }): Promise<void> {
      await executor(db)
        .insert(stockItem)
        .values({ skuId: params.skuId, storeId: params.storeId, onHand: 0, reserved: 0 })
        .onConflictDoNothing({ target: stockItem.skuId });
    },
  };
}
