import js from '@eslint/js';
import tseslint from 'typescript-eslint';

import noMoneyArithmetic from './eslint-rules/no-money-arithmetic.js';
import noRelationalApiInInventory from './eslint-rules/no-relational-api-in-inventory.js';

/**
 * ESLint — baseline.
 *
 * SCOPE NOTE: the type-aware baseline, plus the FIRST of the five custom architecture rules
 * named in docs/DECISIONS.md §5.
 *
 * Landed:      `local/no-money-arithmetic` (§5 rule 5) and
 *              `local/no-relational-api-in-inventory` (§5 rule 4) — see ./eslint-rules/.
 * Outstanding: bare `async` route handlers · `queue.add` outside the event bus · bare `fetch`
 *              outside `integrations/`.
 *
 * Rule 4 landed WITH its subject in Increment 26, which is the policy this comment previously
 * described: the inventory module now exists, so the rule that guards it does too. It guards
 * nothing today — that module deliberately uses an atomic `UPDATE` rather than a row lock —
 * and it must be in place before the allocation increment writes the first genuine
 * `.for('update')`, which is the moment §6's trap becomes live.
 *
 * The three remaining rules still have nothing to guard: there is no queue producer outside
 * the outbox and no `integrations/` directory. They should land with their subjects too. The
 * `dependency-cruiser` contracts (12 of them, all active) cover the module boundaries in the
 * meantime.
 *
 * Do not mistake a green lint for a fully enforced architecture: it is enforced where a rule
 * exists, and reviewed where one does not.
 *
 * Rules here are errors, not warnings. A warning is a rule nobody obeys.
 */
export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'coverage/**',
      'node_modules/**',
      // Generated by drizzle-kit; reviewed as SQL, not linted as source.
      'src/db/migrations/**',
    ],
  },

  js.configs.recommended,

  /**
   * Type-aware linting. Considerably slower than the syntactic rules and worth it: every
   * rule here that catches a real bug (floating promises, unsafe `any`) needs type info.
   *
   * `stylisticTypeChecked` is deliberately NOT enabled. It is opinion, not correctness —
   * it would demand `interface` over `type` across a codebase that uses `type`
   * consistently and on purpose, which is churn in working files for no defect caught.
   */
  ...tseslint.configs.recommendedTypeChecked,

  {
    files: ['**/*.ts'],
    plugins: {
      /**
       * The project's own architecture rules (docs/DECISIONS.md §5). Kept in-repo rather than
       * published: they encode decisions specific to this codebase and must version with it.
       */
      local: {
        rules: {
          'no-money-arithmetic': noMoneyArithmetic,
          'no-relational-api-in-inventory': noRelationalApiInInventory,
        },
      },
    },
    languageOptions: {
      parserOptions: {
        /**
         * Explicit project list rather than `projectService: true`.
         *
         * `tsconfig.json` excludes tests so production builds do not compile them, which
         * leaves test files in no project at all — the project service then refuses to
         * parse them and every test file reports a parsing error instead of being linted.
         * `tsconfig.test.json` covers src + tests; `tsconfig.tools.json` covers the
         * root-level config files.
         */
        project: [
          './tsconfig.test.json',
          './tsconfig.tools.json',
          './packages/contracts/tsconfig.json',
        ],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      /**
       * The single most valuable rule in an async codebase. An un-awaited promise in a
       * request handler or a transaction is a silent partial write and an unhandled
       * rejection — exactly the class of bug the outbox exists to prevent elsewhere.
       */
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',

      /**
       * Off deliberately. It flags every `async` function that satisfies a
       * `Promise<void>`-returning interface without itself awaiting anything — an
       * EventPublisher whose publish is synchronous, a test fake, a shutdown that only
       * calls a sync stop(). Those are correct implementations of an async contract, and
       * the alternative (`return Promise.resolve()`) is worse to read. It catches no
       * bugs here; no-floating-promises catches the ones that matter.
       */
      '@typescript-eslint/require-await': 'off',

      // `any` defeats every other guarantee in the config. Allowed only with an
      // explicit disable comment carrying a reason.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',

      // An unused variable is usually a half-finished edit. `_` prefix opts out.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],

      // Distinguishing null from undefined matters at a database boundary: a nullable
      // column reads back as null, and `== null` quietly conflates the two.
      eqeqeq: ['error', 'always', { null: 'ignore' }],

      // The logger is the only sanctioned output. `console.log` in a server bypasses
      // structured logging, redaction, and the request-id correlation.
      'no-console': 'error',

      'no-restricted-syntax': [
        'error',
        {
          // UUIDv7 is a locked decision — v4 loses the time-ordering that makes it index
          // like a sequence. Use newId() from shared/id.ts.
          selector: "MemberExpression[object.name='crypto'][property.name='randomUUID']",
          message: 'Use newId() from shared/id.ts — randomUUID() produces v4, not UUIDv7.',
        },
      ],

      /**
       * The first of the five §5 architecture rules to land.
       *
       * Type-aware, so it lives in this block rather than in `no-restricted-syntax` — a
       * selector cannot tell a Money amount string from any other string, and that
       * distinction is the entire point of the rule.
       */
      'local/no-money-arithmetic': 'error',

      /**
       * §5 rule 4. Syntactic rather than type-aware on purpose: it must fire even on an
       * `any`-typed handle, which is exactly the case a type-aware rule would miss.
       *
       * Scoped to `src/modules/inventory` by the rule itself rather than by a `files` block,
       * so the scope travels with the rule and cannot be widened by a config edit that looks
       * unrelated.
       */
      'local/no-relational-api-in-inventory': 'error',
    },
  },

  // Tests: the strict `any`-safety rules fight fixtures and assertions for no real gain,
  // and a test that lies about types still fails loudly when it runs.
  {
    files: ['**/__tests__/**/*.ts', '**/*.test.ts', 'tests/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },

  // Scripts and config files run under Node directly and legitimately write to stdout.
  {
    files: ['scripts/**/*.ts', '*.config.ts', 'drizzle.config.ts', 'eslint.config.js'],
    rules: {
      'no-console': 'off',
    },
  },

  // Config files are plain JS and are in no tsconfig, so type-aware rules cannot run against
  // them. Without this they fail to parse rather than skipping.
  //
  // `.cjs` is included for `.dependency-cruiser.cjs`, which must be CommonJS because
  // dependency-cruiser loads its config with `require`.
  {
    files: ['**/*.js', '**/*.cjs'],
    ...tseslint.configs.disableTypeChecked,
  },

  // `.cjs` is CommonJS, so `module` and `require` are real globals rather than undefined
  // identifiers. Declared narrowly here rather than loosening `no-undef` project-wide.
  {
    files: ['**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { module: 'writable', require: 'readonly', __dirname: 'readonly' },
    },
  },
);
